project 'YunWebView.xcodeproj'

source 'https://github.com/CocoaPods/Specs'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
inhibit_all_warnings!

target 'YunWebView' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YunWebView

  pod 'YunBaseApp'
  pod 'YunImgView'

end
